### ISSUE TITLE
Can we change the project description?

### ISSUE THREAD

**Issue by codehangen** [integrativesoft/foton#7]
Hi all.

#### 1. concept
I would like to know if it is possible to change the project description. Can we change the project description?

#### 2.1 github/integrativesoft/foton *before*
![image](https://user-images.githubusercontent.com/111701513/208108308-7a6ac6c0-4f9e-4222-be3a-6ebfdfccd299.png)

#### 2.2 github/integrativesoft/foton *after*
![image](https://user-images.githubusercontent.com/111701513/208108943-836e2a48-ed9b-4317-a838-3e823e245c89.png)

#### 3. question/feedback
*what do you all think of this idea?*

**Comment by pablocar80** [comment]
Done!
